config/routes.rb
HarvestOverflow::Application.routes.draw do
  devise_for :agencies
  resources :overflows
  
  root "overflows#index"
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :overflows

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/overflow.rb
class Overflow < ActiveRecord::Base
  belongs_to :agency

  validates :item_type, :description, :expiration, presence: true
  PERISHABLE = [true, false]
  validates :perishable, inclusion: {in: PERISHABLE}

  def self.most_recent
  	where("created_at >= ?", 2.weeks.ago).order("created_at desc")
  end 
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :name, :address, :city, :state, :zip_code, :phone, :contact) }
  end
end

app/controllers/overflows_controller.rb
class OverflowsController < ApplicationController
	def index
		@agency = Agency.all
		@overflows = Overflow.most_recent
	end

	def new
		@agency = current_agency
		@overflow = @agency.overflows.new
	end

	def create
		@agency = current_agency
		@overflow = @agency.overflows.new(overflow_params)
		if @overflow.save
      		redirect_to root_path, notice: "Thank you for your post!"
    	else
      		render :new
    	end
	end

	def edit
		@overflow = Overflow.find(params[:id])
	end

	def update
    	@overflow = Overflow.find(params[:id])
    	if @overflow.update(overflow_params)
      		redirect_to root_path, notice: "Overflow successfully updated!"
    	else
      		render :edit
    	end
  	end

	def destroy
		@overflow = Overflow.find(params[:id])
		@overflow.destroy
		redirect_to root_path
	end

private
	def overflow_params
		params.require(:overflow).permit(:item_type, :description, :perishable, :expiration)
	end	
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/overflows_helper.rb
module OverflowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>HarvestOverflow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <link href="../../assets/ico/favicon.ico" rel="shortcut icon">
	<!-- Optional theme -->
	<link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/css/main.css">
		<!-- 
	<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>

	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
			
	Latest compiled and minified JavaScript -->
			
	<style type="text/css">
	    .bs-example{
	    	margin: 20px;
	    }
	</style>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

	<div role="navigation" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Harvest Overflow", root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <div role="form" class="navbar-form navbar-right">
			  
        <% if agency_signed_in? %>
			     <%= link_to "Add Overflow", new_overflow_path, class: "btn btn-default" %>
           <%= link_to "Log out", destroy_agency_session_path, method: :delete, class: "btn btn-primary" %>
        <% else %>
           <%= link_to "Log in", new_agency_session_path, class: "btn btn-success" %>
           <%= link_to "Sign up", new_agency_registration_path, class: "btn btn-primary" %>
        <% end %>			

          </div>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
	
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert"><%= alert %></p>
	<% end %>
	
<%= yield %>

</body>
</html>

app/views/overflows/_form.html.erb
<%= form_for(@overflow) do |f| %>
  <%= render "shared/errors", object: @overflow %>
  <fieldset>
    <ol>
      <li>
        <%= f.label :item_type %>
        <%= f.text_field :item_type, autofocus: true %>
      </li>
      <li>
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li>
        <%= f.label :perishable %>
        <%= f.select :perishable, Overflow::PERISHABLE, prompt: "Pick one" %>
      </li>
      <li>
        <%= f.label :expiration %>
        <%= f.date_select :expiration %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", root_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/overflows/edit.html.erb
<header>
  <h1>Edit or Delete Your Overflow</h1>
</header>

<p><%= link_to "Remove from Harvest Overflow", @overflow, method: :delete, data: { confirm: 'Are you sure?' } %></p>

<%= render 'form' %>

app/views/overflows/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron top-message">
      <div class="container">
        <p>Quickly connect with excess goods in your network</p>
      </div>
    </div>

    <div class="container">

			
		
<div class="bs-example">
	
	<% @overflows.each do |overflow| %>
	<h3 class="text-primary">Posted <%= time_ago_in_words(overflow.created_at) %> ago</h3>
    <div class="list-group">
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading"><%= overflow.item_type %></h4>
            <p class="list-group-item-text"><%= overflow.description %></p>
			      <% if overflow.perishable %>
				      <p class="list-group-item-text">Expires <%= time_ago_in_words(overflow.expiration) %> from now</p>
			      <% end %>
            <h4>Pick up location</h4>
            <p>
              <%= @agency.find(overflow.agency_id).name %><br>
              <%= @agency.find(overflow.agency_id).address %><br>
              <%= @agency.find(overflow.agency_id).city %>, 
              <%= @agency.find(overflow.agency_id).state %> 
              <%= @agency.find(overflow.agency_id).zip_code %>
            </p>
            <p>Contact <%= @agency.find(overflow.agency_id).contact %> at <%= @agency.find(overflow.agency_id).phone %></p>
            <p><%= link_to "Update", edit_overflow_path(overflow) %></p>
        </a>
    </div>
	 <% end %>
	 
      <hr>

      <footer>
        <p>&copy; Harvest Overflow 2014</p>
      </footer>
    </div> <!-- /container -->  

app/views/overflows/new.html.erb
<header>
  <h1>Add a New Overflow</h1>
</header>

<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section>
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>